version: "3.4"
services:
  proxy:
    image: traefik-v1.7.9-alpine

  client:
    image: client
    build:
      context: ./client
      dockerfile: ./Dockerfile

  server:
    image: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
